#!/bin/bash

# © 2015 Sebastián González
# http://www.apache.org/licenses/LICENSE-2.0

this=$(realpath "$0")
scripts=$(dirname "$this")

source "$scripts/btrfs-backup-lib.sh"

usage() {
    cat >&2 <<EOF
Usage: $script <src> <pool>

Takes a read-only snapshot of subvolume <src>.
Stores the snapshot in <pool>.

Example: $script / /var/backup
EOF
    exit 1
}

(( $# == 2 )) || usage
src=$1
pool=$2
shift 2

[ -d "$src" ] || die "$src must be a directory"
[ -d "$pool" ] || die "$pool must be a directory"

# Atomic actions.
{
    flock 42

    # Verify that snapshot pool exists (mount if necessary).
    bringUp "$pool"

    name=$(now)
    btrfs subvolume snapshot -r "$src" "$pool/$name" > /dev/null
    echo "Created read-only snapshot $name of $src in $pool"

} 42>"$pool/$lockfile"
