#!/bin/bash

this=$(realpath "$0")
scripts=$(dirname "$this")

source "$scripts/btrfs-backup-lib.sh"

usage() {
    echo "Usage: $script <src> <dest> <store>" >&2
    exit 1
}

[[ $# == 3 ]] || usage

src=$1
base=$2
store=$3
shift 3

[ -n "$src" ] || usage
[ -n "$base" ] || usage
[ -n "$store" ] || usage

"$scripts"/btrfs-backup-snapshot "$src" "$base"
"$scripts"/btrfs-backup-cleanup "$base"

if test -d "$store"; then
    "$scripts"/btrfs-backup-send "$base" "$store"
    "$scripts"/btrfs-backup-cleanup "$store"
fi
