#!/bin/bash

# © 2015 Sebastian Gonzalez
# http://www.apache.org/licenses/LICENSE-2.0

this=$(realpath "$0")
scripts=$(dirname "$this")

source "$scripts/btrfs-backup-lib.sh"

usage() {
    cat >&2 <<EOF
Usage: $script <pool> <dest>

Sends the last snapshot found in <pool> to <dest>.

Example: $script /var/backup /mnt/backup/root

If <dest> resides under a mountable point that is not yet mounted, it will be
mounted and unmouted automatically.
EOF
    exit 1
}

(( $# == 2 )) || usage
pool=$1
dest=$2
shift 2

mounted=false

[ -d "$pool" ] || die "$pool must be a directory"

# Atomic actions on $pool.
{
    flock 42

    # Verify that snapshot pool exists (mount if necessary).
    ensurePool "$dest"

    # Cleanup when done.
    trap 'bringDown "$dest"' EXIT

    # For incremental sending, find most recent snapshot in $dest with
    # a parent in $pool, and store it in $previous. In passing, find
    # most recent snapshot and store it in $last.
    while read previous; do
        if ! [ -v last ]; then
            last=$previous
        fi
        if [ -d "$dest/$(basename "$previous")" ]; then
            break
        fi
    done < <(find "$pool" -mindepth 1 -maxdepth 1 -type d | sort --reverse)

    [ -v last ] || die "No snapshots found in $pool"

    name=$(basename "$last")

    if [ -z "$previous" ]; then
        echo "First submission of $name to $dest"
    else
        if [ "$previous" == "$last" ]; then
            echo "No new snapshots found"
            exit 0
        fi
        echo "Incremental submission of $name to $dest"
    fi

    # btrfs quirk: the snapshots used with 'send' must physically be on disk.
    sync

    if [ -t 2 ] && command -v bar >/dev/null; then
        progress=bar
    else
        progress=cat
    fi

    inProgress=$dest/$name

    ionice -c3 btrfs send ${previous:+-p "$previous"} "$last" | \
        $progress | ionice -c3 btrfs receive "$dest" && \
            unset inProgress

    echo "Sent subvolume $last to $dest"

} 42>"$pool/$lockfile"
