#!/bin/bash

# © 2015 Sebastián González
# http://www.apache.org/licenses/LICENSE-2.0

this=$(realpath "$0" || echo "Please install GNU coreutils" >&2)
scripts=$(dirname "$this")

source "$scripts/btrfs-backup-lib.sh"

usage() {
    cat >&2 <<EOF
Usage: $script <subvol> <pool>

Takes a read-only snapshot of subvolume <subvol>.
Stores the snapshot in <pool>.

Example: $script /home /var/backup/home
EOF
    exit 1
}

(( $# == 2 )) || usage
subvol=$(realpath "$1")
pool=$(realpath "$2")

use-pool "$pool"

name=$(now)
btrfs subvolume snapshot -r "$subvol" "$pool/$name" > /dev/null
echo "Created read-only snapshot $name of $subvol in $pool"
