#!/bin/bash

# © 2015 Sebastian Gonzalez
# http://www.apache.org/licenses/LICENSE-2.0

this=$(realpath "$0")
scripts=$(dirname "$this")

source "$scripts/btrfs-backup-lib.sh"

usage() {
    cat >&2 <<EOF
Usage: $script <pool>

Removes old backups from snapshot pool <pool>.

Example: $script /var/backup
EOF
    exit 1
}

(( $# == 1 )) || usage
pool=$1

[ -d "$pool" ] || die "Snapshot pool $pool must be a directory"

# Atomic actions.
{
    flock 42

    # Verify that snapshot pool exists (mount if necessary).
    ensurePool "$pool"

    now=$(now)
    day=${now%% *}
    month=${day%-*}
    year=${month%-*}

    day() {
        find "$pool" -maxdepth 1 -type d -name "$day*"
    }

    monthButDay() {
        find "$pool" -maxdepth 1 -type d -name "$month*" -not -name "$day*"
    }

    yearButMonth() {
        find "$pool" -maxdepth 1 -type d -name "$year*" -not -name "$month*"
    }

    deleteSnapshots() {
        count=0
        while read snapshot
        do
            btrfs subvolume delete "$snapshot" > /dev/null
            echo "Removed snapshot $snapshot"
            count=$((count+1))
        done
        if ((count > 0)); then
            echo "Cleaned up $count snapshots in $pool"
        fi
    }

    monthButLastInDay() {
        { monthButDay
          monthButDay | sort --reverse | sort --unique --key=1,1
        } | sort | uniq --unique
    }

    # Delete all but last of each day in the month.
    monthButLastInDay | deleteSnapshots

} 42>"$pool/$lockfile"
