#!/bin/bash

# © 2015 Sebastián González
# http://www.apache.org/licenses/LICENSE-2.0

this=$(realpath "$0" || echo "Please install GNU coreutils" >&2)
scripts=$(dirname "$this")

source "$scripts/btrfs-backup-lib.sh"

usage() {
    echo "Usage: $script <subvol> <pool> <store>" >&2
    exit 1
}

(( $# == 3 )) || usage

subvol=$(realpath "$1")
pool=$(realpath "$2")
store=$(realpath "$3")

"$scripts"/btrfs-backup-snapshot "$subvol" "$pool"
"$scripts"/btrfs-backup-send "$pool" "$store"
"$scripts"/btrfs-backup-cleanup "$pool"
"$scripts"/btrfs-backup-cleanup "$store"
