#!/bin/bash

# © 2015–2016 Sebastián González
# http://www.apache.org/licenses/LICENSE-2.0

set -o errexit

this="$(realpath "$0")"
lib="$(dirname "$this")"
script="$(basename "$this")"

source "$lib/common.sh"

usage() {
    cat >&2 <<EOF
Usage: $script <pool> <store>

Copies all subvolumes from <pool> to <store>.

Example: $script /var/backup/home /mnt/external/backup/home
EOF
    exit 1
}

(( $# == 2 )) || usage
pool=$(realpath "$1")
store=$(realpath "$2")

use-pool "$pool"
use-pool "$store"

if [ -t 2 ] && command -v bar >/dev/null; then
    progress=bar
else
    progress=cat
fi

# btrfs quirk: the subvolumes used with 'send' must physically be on disk.
sync

# Copy all subvolumes from $pool to $store,
# proceeding from the oldest to the latest.
copying="Copying the whole of"
while read name; do
    if [ ! -d "$store/$name" ]; then
        echo "$copying subvolume $name to $store"
        inProgress=$store/$name
        ionice -c3 btrfs send ${parent:+-p "$parent"} "$pool/$name" | \
            $progress | ionice -c3 btrfs receive "$store"
        unset inProgress
    fi
    parent="$pool/$name"
    copying="Incrementally copying"
done < <(subvolume-names --ascending "$pool")
