#!/bin/bash

# © 2015–2016 Sebastián González
# http://www.apache.org/licenses/LICENSE-2.0

set -o errexit

this="$(realpath "$0")"
lib="$(dirname "$this")"
script="$(basename "$this")"

source "$lib/common.sh"

usage() {
    cat >&2 <<EOF
Usage: $script <subvolume> <pool>

Takes a read-only snapshot of <subvolume>.
Stores the snapshot in <pool>.

Example: $script /home /var/backup/home
EOF
    exit 1
}

(( $# == 2 )) || usage
subvolume=$(realpath "$1")
pool=$(realpath "$2")

use-pool "$pool"

name=$(now)
btrfs subvolume snapshot -r "$subvolume" "$pool/$name" > /dev/null
echo "Created read-only snapshot $name of $subvolume in $pool"
